services:

  apache-static:
    build: ./apache-static
    ports:
      - "82:80"

  nginx-static:
    build: ./nginx-static
    ports:
      - "94:80"

  node-dynamic:
    build: ./node-dynamic
    ports:
      - "86:3000"

  flask-dynamic:
    build: ./flask-dynamic
    ports:
      - "88:5000"
